import random
from datetime import datetime
import os

# Daily coding quotes
quotes = [
    "Code is like humor. When you have to explain it, it's bad. — Cory House",
    "First, solve the problem. Then, write the code. — John Johnson",
    "The best error message is the one that never shows up. — Thomas Fuchs",
    "Code never lies, comments sometimes do. — Ron Jeffries",
    "Programming isn't about what you know; it's about what you can figure out. — Chris Pine",
    "The only way to learn a new programming language is by writing programs in it. — Dennis Ritchie",
    "It's not a bug; it's an undocumented feature. — Anonymous",
    "Clean code always looks like it was written by someone who cares. — Robert C. Martin",
    "The most important property of a program is whether it accomplishes the intention of its user. — C.A.R. Hoare",
    "Simplicity is the soul of efficiency. — Austin Freeman",
    "Talk is cheap. Show me the code. — Linus Torvalds",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. — Martin Fowler",
]

# Motivational messages
motivations = [
    "Keep coding, keep growing! 🚀",
    "Every line of code brings you closer to mastery! 💪",
    "Today's code is tomorrow's innovation! ✨",
    "Stay curious, stay coding! 🎯",
    "Building the future, one commit at a time! 🔥",
    "Consistency is the key to success! 🌟",
    "Debug today, deploy tomorrow! 💻",
    "Learn something new every day! 📚",
]

# Generate content
now = datetime.now()
quote = random.choice(quotes)
motivation = random.choice(motivations)
day_of_year = now.timetuple().tm_yday

content = f"""# 📅 Daily Update — {now.strftime('%B %d, %Y')}

---

## 💡 Quote of the Day

> *"{quote}"*

---

## 🔥 Daily Motivation

**{motivation}**

---

## 📊 Quick Stats

| Metric | Value |
|--------|-------|
| 📆 Day of Year | {day_of_year} |
| 📅 Date | {now.strftime('%Y-%m-%d')} |
| ⏰ Time | {now.strftime('%H:%M:%S')} UTC |
| 🎯 Days Coding Streak | Keep it going! |

---

## 🎯 Today's Challenge

```
Today's Goal: Write at least 50 lines of meaningful code.

Remember:
✅ Solve one DSA problem
✅ Review and refactor old code
✅ Learn one new concept
✅ Push your progress
```

---

## 🌟 Fun Fact

Did you know? The first computer bug was an actual bug — a moth found trapped in a Harvard Mark II computer in 1947!

---

*Auto-generated by GitHub Actions | Last updated: {now.strftime('%Y-%m-%d %H:%M:%S')}*

⭐ Keep pushing! Your consistency is your superpower!
"""

# Write to DAILY.md
with open('DAILY.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("Daily content generated for " + now.strftime('%Y-%m-%d'))
